### PR TITLE
7874 cache cms articles

### PR DESCRIPTION
**Pull request by tomas-stefano**
This is related to moneyadviceservice/cms#372

In order to the the CMS PR works I needed to add the line on the manageable module on comfy.

IMHO this module is absolutely unnecessary because we can move to the PageRegister but it is not scope for the cache work so I will add a card to return on this tech debt.

### CODE REVIEW

**Comment by tomas-stefano** [comment]
Just to be documented. The Comfy and CMS has a property on the page that is called "content_cache" but it is a default from Comfy and does not use the Mastalk gem and uses some not organised code on the lib directory. So I decide to add a columns processed_content that solves the issue. If you have a better idea I am open to new ideas.

**Comment by rnalexander** [comment]
:+1:

**Comment by norm** [comment]
Could the explanation be put in the commit so it is directly accessible when viewing git history, rather than being only indirectly findable via GitHub?

**Comment by tomas-stefano** [comment]
@norm done! ♻️

**Comment by norm** [comment]
👍

**Comment by tomas-stefano** [comment]
I added more commits to this PR. Can it be reviewed again, please?

**Comment by rnalexander** [comment]
LGTM!  :+1:

**Pull request merged**
