### PR TITLE
[DEV APPROVED]Ruby 2.3.3

### PR DESCRIPTION
**Pull request by jriga**
**Upgrade**
from 2.1.2 -> 2.3.3

### CODE REVIEW

**Comment by jongilbraith** [comment]
You'll need to update [rvm in puppet](https://github.com/moneyadviceservice/scripts/blob/master/puppet/modules-local/ruby/manifests/init.pp#L36) too.

**Comment by jongilbraith** [comment]
Well, assuming you're going to update cms too of course. 🙂

**Comment by jriga** [comment]
Thanks for the heads up 👍

**Comment by jongilbraith** [comment]
👍

**Comment by rnalexander** [comment]
:+1: :shipit:

**Pull request merged**
