### PR TITLE
Reload everytime you update is mirrored attribute

### PR DESCRIPTION
**Pull request by tomas-stefano**
Everytime you destroy a site Comfy will set the self to not mirror anymore
but the attribute is_mirrored is using the old value and not the new
one (because they are using update_all), so reloading the database record
after the update will solve the issue and will make the test pass

### CODE REVIEW

**Comment by Tr4pSt3R** [comment]
👍 👍

**Comment by norm** [comment]
Are the whitespace changes necessary to fix this? If not, could they be in a separate commit?

**Comment by tomas-stefano** [comment]
No they aren't necessarily. Why do you think it is better to be in a separate commit?

**Comment by tomas-stefano** [comment]
No they aren't necessarily. Why do you think it is better to be in a separate commit?

**Comment by norm** [comment]
Because they aren't necessary.

**Comment by norm** [comment]
Then don't commit the whitespace changes at all, since they are irrelevant? Either way 👍.

**Comment by tomas-stefano** [comment]
Actually besides the whitespace there is newline on the of file and rubocop complains about it. So it make worth to add the new line and I took the opportunity to clean the whitespace in the PR. I will merge now.

**Pull request merged**
